name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet==0.85.2
          pip install -r requirements.txt

      - name: Build APK (Non-interactive)
        run: |
          yes | flet build apk --verbose \
            --android-permissions android.permission.WRITE_EXTERNAL_STORAGE \
            --android-permissions android.permission.READ_EXTERNAL_STORAGE \
            --android-permissions android.permission.MANAGE_EXTERNAL_STORAGE

      - name: Show build result
        run: ls -R build/ || echo "Build folder not found"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Anbar-App-APK
          path: |
            build/*.apk
            build/apk/*.apk
          if-no-files-found: warn
